### ISSUE TITLE
Fullscreen on MAC

### ISSUE THREAD

**Issue by Benni172** [danielknobe/blobbyvolley2#11]
There is a bug if you choose fullscreen on a macbook it scales wrong and you are only able to see one half of the game and there is no possibility to change it back - even deleting and reinstalling the game won't change back the settings to window mode

**Comment by danielknobe** [comment]
Hi Benni,
are you using the version 1.0 release or the latest source code from github?
Which version of MacOS are you using?

**Comment by danielknobe** [comment]
Closed because of inactivity.
