### ISSUE TITLE
Blobby Volley 2 doesn't find opponent for online play

### ISSUE THREAD

**Issue by rostbacke** [danielknobe/blobbyvolley2#147]
Steps to reproduce:
(Find a second player with own computer) > both open https://blobbyvolley.de/data/bv2browser/index.html > both select "Online" > (both wait on screen "Waiting for opponent")

Expected result: Matchmaking connects both players and they can play
Actual result: Stuck on screen "Waiting for opponent"

Environment: Edge 123.0.2420.65 (Official build) (64-bit), Chrome 123.0.6312.86 (Offizieller Build) (64-Bit)

Online play is impossible right now, because the game cannot connect online players.

**Comment by elkangaroo** [comment]
The online version tries to connect to https://blobbyvolley.de:12345/socket.io/
and it looks like the Letsencrypt Certificate there expired:
![image](https://github.com/danielknobe/blobbyvolley2/assets/1144202/dd2609d3-126f-4ce2-87e2-0463ba5f95e8)

The Letsencrypt Certificate on https://blobbyvolley.de seems to be renewed correctly, so they probably forgot to update it in whatever tool is running on Port 12345.

**Comment by danielknobe** [comment]
I just restarted the server to refresh the cert. When I find some time I will get this fixed by autoreload the cert.

**Comment by rostbacke** [comment]
It works again! Thank you very much! (Working from home is safe again! :) )
