### ISSUE TITLE
Czech translation for Blobby Volley

### ISSUE THREAD

**Issue by pafri** [danielknobe/blobbyvolley2#19]
Hi,

it is almost seven years when I've translated the VB2 into Czech language, but somehow I don't see it among the localization files, even if I remember I had sent it to original Blobby Volley project (?). Also attached.
[lang_cs.zip](https://github.com/danielknobe/blobbyvolley2/files/6144245/lang_cs.zip)

**Comment by danielknobe** [comment]
Hi,
thank you very much for the translation. I added it and mapped the special characters to ASCII characters.
This looks like that:
![Unbenannt](https://user-images.githubusercontent.com/54905085/111843879-39f17f00-8902-11eb-956f-6fe984ba43de.jpg)

I do not speak Czech, but I hope that this is good enough?

**Comment by pafri** [comment]
Left player/Right player - if these strings are included in the file (?), then they should be translated too.

I's about 7 years, when I've made the translation of the file. Should I complete it?

Left player -> Hráč vlevo
Right player -> Hráč vpravo

**Comment by danielknobe** [comment]
The "Left player" and "Right player" text you are seeing are the player names. They doesn't need a translation.
The only missing translations are the following:
"join game"
"leave game"
"open game"
"points: "

**Comment by pafri** [comment]
Here are the translations
"join game" -> Připojit se ke hře
"leave game" -> Opustit hru
"open game" -> Otevřít hru
"points: " -> Body:

**Comment by pafri** [comment]
show blood -> Ukázat krev
show jelly -> Ukázat želé

**Comment by danielknobe** [comment]
Added. Thx.
I think this issue is done.
Please close it.
