### ISSUE TITLE
Some questions about this project

### ISSUE THREAD

**Issue by TomaszGasior** [danielknobe/blobbyvolley2#2]
Sorry for writing here. I know, it's bug tracker but I don't understand German on http://blobbyvolley.de/ .

Where is the official repository for blobby volley development? Here or in https://sourceforge.net/projects/blobby/files? Is this game actively developed (or meant to be)? :)

**Comment by TomaszGasior** [comment]
Also, which commit in this repo points to the newest stable version of the game (if any)?

**Comment by danielknobe** [comment]
Hallo Tomasz,
no problem.
This github repository is the new official repository of the project.
The repository on sourceforge is deprecated.
There is a commit for the last stable version but it is not tagged. You can download the source of the latest stable release (1.0 stable) here: https://sourceforge.net/projects/blobby/files/Blobby%20Volley%202%20%28Linux%29/1.0/blobby2-linux-1.0.tar.gz/download

**Comment by TomaszGasior** [comment]
I guess it's around this: https://github.com/danielknobe/blobbyvolley2/commit/bff472b1c189a30ad14685e3d4d89c927b587b2e

Thank you! I hope to see new releases in the future. :)

**Comment by Mailaender** [comment]
It would be great if you tag that commit, so it can be properly packaged.

**Comment by TomaszGasior** [comment]
You can take a look at Flatpak package with Blobby Volley to get exact commit to make it packaged: https://github.com/flathub/de.blobbyvolley.BlobbyVolley2/blob/6a37c7afe9b9a5c32ecf90b85d9f3af251e6df05/de.blobbyvolley.BlobbyVolley2.yaml#L39

**Comment by danielknobe** [comment]
Good idea ;). Done.

**Comment by Mailaender** [comment]
Okay, I upgraded (or downgraded?) accordingly at https://build.opensuse.org/request/show/859296

**Comment by danielknobe** [comment]
Seems to be a small downgrade. The currently used version in OpenSuse has some fixes by using a newer version which is no offical release.
