### ISSUE TITLE
Missing italian translations

### ISSUE THREAD

**Issue by danielknobe** [danielknobe/blobbyvolley2#21]
The following translations are missing in lang_it.xml:
" by "
"arrow keys"
"blobby follows finger"
"challenger: "
"games: "
"join game"
"leave game"
"open game"
"points: "
"random"
"rules:"
"rules: "
"speed: "
"stay on server"
"touch input type:"

"show blood" will be changed to "show jelly" in the future to have the translation more suitable for children. What's the right translation for italian?

**Comment by ngc92** [comment]
instead of "show jelly", should we go with the more general "particle effects"?

**Comment by danielknobe** [comment]
Fixed by #128
