### ISSUE TITLE
Matchmaking doesnt work

### ISSUE THREAD

**Issue by Nikvrasu** [danielknobe/blobbyvolley2#22]
connection refused

**Comment by danielknobe** [comment]
Can you please describe the problem in more detail (blobby version, OS version)?
What have you done to get this error?

**Comment by Nikvrasu** [comment]
Hey,
Ich hab dir diese Mail vor mehreren Monaten gesendet und du hast das
Problem bereits gefixed.
Mfg

Am So., 25. Sept. 2022 um 09:46 Uhr schrieb Daniel Knobe <
***@***.***>:
