### ISSUE TITLE
Dangling references from exceptions `.what()`

### ISSUE THREAD

**Issue by ngc92** [danielknobe/blobbyvolley2#31]
Some of the exception types defined in `FileExceptions.h` build a `std::string` and return its `.c_str()` in their `what()` function, meaning the returned char pointer points to the memory of a deleted string. 

I'm not sure what the best way to fix this is, the entire code there seems a bit overengineered for the needs of blobby.

**Comment by danielknobe** [comment]
You are right. The Exceptions here seem completely broken. Feel free to fix it :).
