### ISSUE TITLE
Blobs colors are off on big endian archs

### ISSUE THREAD

**Issue by julianaito** [danielknobe/blobbyvolley2#4]
Hi,

While playing on my old 32-bit PowerPC Mac running OpenBSD/macppc, i've found out that blobs colors are off, only on SDL mode (OpenGL is fine). The problem is more complex than swapping red and blue, and that `fak` thing gets in the mix ;)

I'm running out of ideas after trying many things, mostly because i don't really how SDL works in this regard. 

I would be happy to try a potential fix :)

![capture_2020-02-03_120312_28531](https://user-images.githubusercontent.com/41287367/73648253-72da8000-467d-11ea-9813-60c2f66b11bc.png)

**Comment by danielknobe** [comment]
Hello julianaito,
thank you for the report. Blobby Volley 2 should work on every system including PowerPC ;).
I have created a fix which may solves the problem. I have no PowerPC to test it.
Can you please verify the patch?

Best regards,
Daniel

**Comment by julianaito** [comment]
Hello,

It works like a charm, mixing primary colors gives also the proper colors. Thanks a lot!

![2020-02-08-233826_1708x640_scrot](https://user-images.githubusercontent.com/41287367/74093021-bc3b2d00-4acc-11ea-807d-05dc2ecdc4f0.png)

**Comment by danielknobe** [comment]
That's great :+1: . Thank you very much for the validation and the report & screenshot.
If you run into other issues let me know.
