### ISSUE TITLE
Physfs setup on Android

### ISSUE THREAD

**Issue by ngc92** [danielknobe/blobbyvolley2#54]
Recently, physfs added the following to its documentation regarding Android:
```
 * \warning On Android, argv0 should be a non-NULL pointer to a
 *          PHYSFS_AndroidInit struct. This struct must hold a valid JNIEnv *
 *          and a JNI jobject of a Context (either the application context or
 *          the current Activity is fine). Both are cast to a void * so we
 *          don't need jni.h included wherever physfs.h is. PhysicsFS
 *          uses these objects to query some system details. PhysicsFS does
 *          not hold a reference to the JNIEnv or Context past the call to
 *          PHYSFS_init(). If you pass a NULL here, PHYSFS_init can still
 *          succeed, but PHYSFS_getBaseDir() and PHYSFS_getPrefDir() will be
 *          incorrect.
 ```
 
 We are not doing this, but then we are currently not using `PHYSFS_getBaseDir()` for Android, so maybe this is not a problem. *But* we are still passing `argv[0]`, which may not be a `nullptr`.

**Comment by danielknobe** [comment]
I will check this when I building the next time for Android.
SDL2 seems to have all the little helper we need:
[SDL_AndroidGetJNIEnv](https://wiki.libsdl.org/SDL2/SDL_AndroidGetJNIEnv)
[SDL_AndroidGetActivity](https://wiki.libsdl.org/SDL2/SDL_AndroidGetActivity)
