### ISSUE TITLE
Crash on play any replay

### ISSUE THREAD

**Issue by danielknobe** [danielknobe/blobbyvolley2#77]
On linux I get the following error:

loaded rules BV2 Default Rules by Blobby Volley 2 Developers from server_rules.lua
blobby: /home/danielknobe/repos/release/src/state/State.cpp:48: void State::playSound(const string&, float): Assertion `m_App' failed.
Abgebrochen (Speicherabzug geschrieben)

**Comment by ngc92** [comment]
Fortunately, this seems to be a relatively simple problem. We are only setting the main app at the "switchState" call, yet the "loadReplay" function is called before that happens, and in itself tries to play a sound. 
This should be a simple fix, we just play the sound as part of the `init` call, but I'd like to add "play a short replay" to the sequence of actions that we test in the CI along with the fix.
