### ISSUE TITLE
Crash on MacOs Ventura

### ISSUE THREAD

**Issue by trenchbear** [danielknobe/blobbyvolley2#79]
After updating to MacOS Ventura 13.1 the game fails to start with an OS message "Failed to start". 
After that the Gui freezes and the Mac reboots after some time.

**Comment by danielknobe** [comment]
Thank you for the bug report.
Which version of blobby volley 2 are you using. The current one in the download section of blobbyvolley.de or a self build from GitHub?

**Comment by trenchbear** [comment]
Thanks for the quick response!
I'm using the brew version. It uses [this download link](https://downloads.sourceforge.net/blobby/blobby2-macosx-1.0.dmg).

**Comment by danielknobe** [comment]
I can confirm, this old version is broken on a clean installation of MacOS Ventura 13.1. Build from latest git seems to work, so with the next version of blobby volley 2 the problem is solved.

**Comment by M3r0wing3r** [comment]
Only a note, but i checked out the latest version from github and build it locally (mac), but i wasn't able to start the game, since the opening window freezed and remained black.

**Comment by trenchbear** [comment]
Thanks @danielknobe, it worked for me.
Only question left is, when starting an online game and choosing blobby volley 2 server, how to change the game speed. Seems like only 100% is possible.

**Comment by danielknobe** [comment]
Hi @trenchbear ,
fix is merged and the server on blobbyvolley.de is updated. Please try again ;).
You can close the issue if everything works as aspected.

**Comment by trenchbear** [comment]
Hi @danielknobe ,
actually I have one more question: I updated to the latest master version and don't see any public servers. Is this intended behaviour?
Thanks for your support!

**Comment by danielknobe** [comment]
The server service has crashed some days ago with the following error:

`A process of this unit has been killed by the OOM killer. 
Main process exited, code=exited, status=137/n/a
Failed with result 'oom-kill'.`

I restarted it with some minor changes. I think it will crash again because there seems to be an memory issue.

**Comment by trenchbear** [comment]
Alright, I'll close this issue then since the original problem is resolved.
